import type { Metadata } from "next";
import { Inter, Patrick_Hand } from "next/font/google";
import "./globals.css";
import { Organism } from "./_components/organisms";

const inter = Inter({ subsets: ["latin"] });
const englebert = Patrick_Hand({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={englebert.className}>
        <Organism.Navbar />
        {children}
        <Organism.Footer />
      </body>
    </html>
  );
}
